all: CurrentDate.obj

CurrentDate.obj: CurrentDate.cpp
	cl CurrentDate.cpp
	copy CurrentDate.exe C:\Users\Андрей\GitHub\SPbCT_GanushkinAP_LyagicevaKA\ControlWork\bin
	del C:\Users\Андрей\GitHub\SPbCT_GanushkinAP_LyagicevaKA\ControlWork\bin\CurrentDate.exe
clean:
	del C:\Users\Андрей\GitHub\SPbCT_GanushkinAP_LyagicevaKA\ControlWork\CurrentDate\CurrentDate.exe
	del C:\Users\Андрей\GitHub\SPbCT_GanushkinAP_LyagicevaKA\ControlWork\CurrentDate\CurrentDate.obj
